name: Set up scaffold

on:
  workflow_dispatch:
    inputs:
      repo-owner:
        description: Samples repo owner
        default: microsoft
        required: true
      repo-name:
        description: Samples repo owner
        default: BotBuilder-Samples
        required: true
      repo-branch:
        description: Samples repo branch
        default: main
        required: true
      folder:
        description: Samples folder
        default: samples/javascript_nodejs/02.echo-bot
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone repository
        run: |
          curl -Lo /tmp/main.zip https://github.com/${{ github.event.inputs.repo-owner }}/${{ github.event.inputs.repo-name }}/archive/refs/heads/${{ github.event.inputs.repo-branch }}.zip
          unzip /tmp/main.zip */${{ github.event.inputs.folder }}/* -d /tmp/samples-repo/
          cp -r /tmp/samples-repo/${{ github.event.inputs.repo-name }}-${{ github.event.inputs.repo-branch }}/${{ github.event.inputs.folder }}/* .
          ls -lAR
